--- #YAML:1.0
name:               OIS
version:            0.10
abstract:           Perl binding for the OIS C++ input framework
author:
    - Scott Lanning <slanning@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::ParseXS:  2.2206
requires:
    Scalar::Util:  1.18
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
