# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OIS
version:      0.03
version_from: OIS.pm
installdirs:  site
requires:
    Scalar::Util:                  1.18
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
